# Form implementation generated from reading ui file '../app/ui\welcome_interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from app.utils import get_abs_path


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 309)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet(
            "QWidget#widget {\n"
            "    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 148, 157, 255), stop:0.890052 rgba(255, 177, 177, 255));\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_label = QtWidgets.QLabel(parent=self.widget)
        self.welcome_label.setStyleSheet(
            "color: rgb(255, 255, 255);\n" 'font: 30pt "Ubuntu";'
        )
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout.addWidget(
            self.welcome_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_button = QtWidgets.QToolButton(parent=self.widget)
        self.img_button.setStyleSheet(
            "QToolButton {\n"
            '    font: 15pt "Ubuntu";\n'
            "    background-color: transparent;\n"
            "    border: 1px solid transparent;\n"
            "    color: #FFFFFF; /* Couleur du texte */\n"
            "}\n"
            "\n"
            "QToolButton:hover {\n"
            "    background-color: rgba(0, 0, 0, 0.2); /* Couleur de fond lorsqu'il est survolé */\n"
            "}\n"
            "\n"
            "QToolButton:pressed {\n"
            "    background-color: rgba(0, 0, 0, 0.4); /* Couleur de fond lorsqu'il est cliqué */\n"
            "}"
        )
        self.img_button.setCheckable(True)
        self.img_button.setObjectName("img_button")
        self.horizontalLayout_2.addWidget(self.img_button)
        self.img_box = QtWidgets.QCheckBox(parent=self.widget)
        self.img_box.setEnabled(False)
        self.img_box.setMaximumSize(QtCore.QSize(131, 16777215))
        self.img_box.setStyleSheet(
            "QCheckBox::indicator {\n" "    width: 23px;\n" "    height: 23px;\n" "}"
        )
        self.img_box.setText("")
        self.img_box.setCheckable(True)
        self.img_box.setObjectName("img_box")
        self.horizontalLayout_2.addWidget(self.img_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.seg_button = QtWidgets.QToolButton(parent=self.widget)
        self.seg_button.setStyleSheet(
            "QToolButton {\n"
            '    font: 15pt "Ubuntu";\n'
            "    background-color: transparent;\n"
            "    border: 1px solid transparent;\n"
            "    color: #FFFFFF; /* Couleur du texte */\n"
            "}\n"
            "\n"
            "QToolButton:hover {\n"
            "    background-color: rgba(0, 0, 0, 0.2); /* Couleur de fond lorsqu'il est survolé */\n"
            "}\n"
            "\n"
            "QToolButton:pressed {\n"
            "    background-color: rgba(0, 0, 0, 0.4); /* Couleur de fond lorsqu'il est cliqué */\n"
            "}"
        )
        self.seg_button.setObjectName("seg_button")
        self.horizontalLayout_3.addWidget(self.seg_button)
        self.seg_box = QtWidgets.QCheckBox(parent=self.widget)
        self.seg_box.setEnabled(False)
        self.seg_box.setMaximumSize(QtCore.QSize(131, 16777215))
        self.seg_box.setStyleSheet(
            "QCheckBox::indicator {\n" "    width: 23px;\n" "    height: 23px;\n" "}"
        )
        self.seg_box.setText("")
        self.seg_box.setCheckable(True)
        self.seg_box.setObjectName("seg_box")
        self.horizontalLayout_3.addWidget(self.seg_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.continue_button = QtWidgets.QPushButton(parent=self.widget)
        self.continue_button.setStyleSheet(
            "QPushButton {\n"
            "    background-color: transparent;\n"
            "    border: 1px solid transparent;\n"
            "    color: #FFFFFF; /* Couleur du texte */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgba(0, 0, 0, 0.2); /* Couleur de fond lorsqu'il est survolé */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgba(0, 0, 0, 0.4); /* Couleur de fond lorsqu'il est cliqué */\n"
            "}\n"
            "\n"
            ""
        )
        self.continue_button.setObjectName("continue_button")
        self.verticalLayout.addWidget(self.continue_button)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_label.setText(_translate("Dialog", "Welcome"))
        self.img_button.setText(_translate("Dialog", "Image file"))
        self.seg_button.setText(_translate("Dialog", "Segmentation file"))
        self.continue_button.setText(_translate("Dialog", "Continue"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
